function Hd = Bird1_Bandstop
%BIRD1_BANDSTOP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 20-Nov-2024 02:07:50

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 22050;  % Sampling Frequency

Fpass1 = 3150;              % First Passband Frequency
Fstop1 = 3500;              % First Stopband Frequency
Fstop2 = 5500;              % Second Stopband Frequency
Fpass2 = 5900;              % Second Passband Frequency
Dpass1 = 0.028774368332;    % First Passband Ripple
Dstop  = 3.1622776602e-05;  % Stopband Attenuation
Dpass2 = 0.028774368332;    % Second Passband Ripple
dens   = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
