function Hd = Bird3_Bandpass2
%BIRD3_BANDPASS2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 20-Nov-2024 04:30:58

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 22050;  % Sampling Frequency

Fstop1 = 5350;              % First Stopband Frequency
Fpass1 = 5450;              % First Passband Frequency
Fpass2 = 5550;              % Second Passband Frequency
Fstop2 = 5650;              % Second Stopband Frequency
Dstop1 = 3.1622776602e-05;  % First Stopband Attenuation
Dpass  = 0.028774368332;    % Passband Ripple
Dstop2 = 3.1622776602e-05;  % Second Stopband Attenuation
dens   = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
